epochs: 20
data: datasets/yolo_koala_kangaroo.v1-original.yolov11/data.yaml
# no_aug.yaml

# Augmentation settings
degrees: 0.0 # image rotation (degrees)
translate: 0.0 # image translation (fraction)
scale: 0.0 # image scale (scale factor)
shear: 0.0 # image shear (degrees)
perspective: 0.0 # image perspective (degrees)
flipud: 0.0 # image up/down flip (probability)
fliplr: 0.0 # image left/right flip (probability)
mosaic: 0.0 # mosaic probability
mixup: 0.0 # mixup probability
copy_paste: 0.0 # copy-paste probability
auto_augment: None # set to None to disable auto_augment (classification only)

# HSV augmentation
hsv_h: 0.0 # image HSV-Hue (fraction)
hsv_s: 0.0 # image HSV-Saturation (fraction)
hsv_v: 0.0 # image HSV-Value (fraction)

# Other settings
# You can also set 'close_mosaic' to 0 to ensure it is never used.
close_mosaic: 0
