epochs: 30
hsv_h: 0.0
hsv_s: 0.0
hsv_v: 0.0
translate: 0.5
scale: 0.5
fliplr: 0.0
mosaic: 0.0
erasing: 0.0
degrees: 10.0
shear: 10.0
perspective: 0.001
# failed experiments as it deteriorates performance and detect nothing
# "datasets/yolo_koala_kangaroo v3.v1i.yolov11/data.yaml"