up:
	podman compose up
	open http://localhost:8080
up-labelstudio:
	podman compose up -d labelstudio
	open http://localhost:8080
up-dino:
	podman compose up -d grnddino
down:
	podman compose down
logs:
	podman compose logs -f
